# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcf29a586512b439a72a33e977f8d98fb9a5d57347b28e334be2825f157c7cf498c206e3d9f837189868c62a5cc86086c3e1a04b1fb93653fddc7f2de1fe635f

test:
  secret_key_base: 7fdd3af6c25cf8cd7c1c40412dfd3e8207e22b44b27fcab12a0573c598a3173a7b4addc8497c46cb252aa5d6223fb32f60da5897c55ad5a4241046a47e4a4653

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
